version: '2'
services:
        vid-server:
                image: ecomp-nexus:51212/ecomp/vid
                ports:
                - "8080:8080"
                links:
                - vid-mariadb:vid-mariadb-docker-instance
        vid-mariadb:
                image: ecomp-nexus:51212/mariadb:10.1.11
                ports:
                - "3306:3306"
                volumes:
                - /var/lib/mysql
