export enum DrawingBoardModes {
  RETRY = 'RETRY',
  RETRY_EDIT = 'RETRY_EDIT',
  VIEW = 'VIEW',
  EDIT = 'EDIT',
  OLD_VIEW_EDIT = 'OLD_VIEW_EDIT',
  CREATE = 'CREATE',
  RECREATE = 'RECREATE',
  RESUME = 'RESUME'
}
